const fs=require('fs'),vm=require('vm'),path=require('path'),init=require('sql.js'),assert=require('assert');
(async()=>{
const SQL=await init();const script=fs.readFileSync('public/worker.js','utf8');let response;
const scope={self:{},initSqlJs:()=>Promise.resolve(SQL),postMessage:r=>response=r};scope.self=scope;scope.importScripts=(...files)=>files.forEach(f=>{if(f==='data.js')vm.runInContext(fs.readFileSync('public/data.js','utf8'),scope);});vm.createContext(scope);vm.runInContext(script,scope);
async function run(data){response=null;await scope.onmessage({data:{id:1,...data}});return response;}
for(const g of scope.GROUPS)for(const e of g.exercises){const r=await run({type:'run',sql:e.solution,exercise:e});assert(r.ok&&r.correct,e.id+': '+JSON.stringify(r));}
const e=scope.GROUPS[0].exercises[0];assert(!(await run({type:'run',sql:'SELEC * FROM productos;',exercise:e})).ok);assert(!(await run({type:'run',sql:'SELECT nombre FROM productos;',exercise:e})).correct);assert(!(await run({type:'run',sql:'SELECT * FROM productos; SELECT * FROM clientes;',exercise:e})).ok);assert((await run({type:'run',sql:'-- comentario\nselect * from productos',exercise:e})).correct);assert(!(await run({type:'run',sql:'UPDATE productos SET precio=0;',exercise:e})).ok);assert(!(await run({type:'run',sql:'INSERT INTO pedidos VALUES(11,999,\'2026-04-01\',1,\'pendiente\');',free:true})).ok);
const {JSDOM}=require('jsdom');const dom=new JSDOM(fs.readFileSync('public/index.html','utf8'),{url:'http://localhost:3000',runScripts:'outside-only'});const w=dom.window;w.Worker=class{postMessage(data){run(data).then(r=>this.onmessage({data:{...r,id:data.id}}));}terminate(){}};
w.eval(fs.readFileSync('public/data.js','utf8'));w.eval(fs.readFileSync('public/app.js','utf8'));const wait=()=>new Promise(r=>setTimeout(r,80));await wait();assert.equal(w.document.querySelectorAll('.topic').length,15);assert.equal(w.document.querySelectorAll('#dataset tbody tr').length,12);assert(!w.document.getElementById('run').disabled);w.document.getElementById('editor').value=e.solution;w.document.getElementById('run').click();await wait();assert(w.document.getElementById('feedback').textContent.includes('¡Correcto!'));assert.equal(w.document.getElementById('score').textContent,'1 / 75');w.document.getElementById('next').click();assert.equal(w.document.getElementById('title').textContent,'Solo lo necesario');w.document.getElementById('expected-toggle').click();await wait();assert(!w.document.getElementById('expected').hidden);w.document.getElementById('editor').value='SELECT missing FROM productos;';w.document.getElementById('run').click();await wait();assert(w.document.getElementById('feedback').textContent.includes('no such column'));w.document.getElementById('free').click();assert.equal(w.document.getElementById('title').textContent,'Explora a tu ritmo');dom.window.close();console.log('PASS: 75 worker corrections; invalid syntax, wrong result, multiple statements, foreign keys, navigation, expected results, local progress and free mode.');
})();
